package rpg.templateData;

public class NPCData {

    public static final String[] NAMES = {
            "Aria", "Borin", "Cyrus", "Daria", "Elric", "Fiona", "Gareth", "Helena", "Ivar", "Jora",
            "Korin", "Lira", "Marek", "Nadia", "Orin", "Perrin", "Quin", "Rina", "Soren", "Talia",
            "Ulric", "Vera", "Wren", "Xander", "Yara", "Zorin", "Alden", "Brynn", "Calix", "Damon",
            "Eira", "Fenric", "Galen", "Hale", "Inara", "Jarek", "Kendra", "Loren", "Mira", "Nolan",
            "Oriana", "Pax", "Quill", "Raven", "Silas", "Talon", "Una", "Vaughn", "Willow", "Xenia",
            "Yvonne", "Zane", "Ava", "Blaze", "Corin", "Dahlia", "Eldon", "Frey", "Giselle", "Hector",
            "Irene", "Jovan", "Keira", "Lance", "Maeve", "Nico", "Ophelia", "Preston", "Quentin", "Rhea",
            "Stellan", "Thalia", "Ulani", "Vesper", "Wynn", "Xavi", "Yvette", "Zella", "Aiden", "Bella",
            "Caden", "Delilah", "Emery", "Felix", "Gemma", "Hayden", "Isla", "Jasper", "Kiera", "Liam",
            "Maya", "Noah", "Olivia", "Piper", "Quincy", "Ruby", "Sebastian", "Tessa", "Ulysses", "Violet",
            "Wyatt", "Xander", "Yara", "Zara", "Asher", "Briar", "Cleo", "Dante", "Elena", "Finn",
            "Greta", "Hugo", "Ivy", "Juno", "Kai", "Luna", "Milo", "Nina", "Oscar", "Paige",
            "Quinn", "Rory", "Sage", "Theo", "Uma", "Vera", "Willa", "Xena", "Yara", "Zane",
            "Ari", "Blaise", "Cyrus", "Dahlia", "Ezra", "Freya", "Gideon", "Harlow", "Iris", "Jett",
            "Koa", "Lark", "Mira", "Nash", "Orla", "Pax", "Quillan", "Rhea", "Soren", "Tess",
            "Uriah", "Veda", "Wren", "Xanthe", "Yara", "Zuri", "Alden", "Briar", "Cyrus", "Dahlia",
            "Ezra", "Freya", "Gideon", "Harlow", "Iris", "Jett", "Koa", "Lark", "Mira", "Nash",
            "Orla", "Pax", "Quillan", "Rhea", "Soren", "Tess", "Uriah", "Veda", "Wren", "Xanthe",
            "Yara", "Zuri", "Alden", "Briar", "Cyrus", "Dahlia", "Ezra", "Freya", "Gideon", "Harlow",
            "Iris", "Jett", "Koa", "Lark", "Mira", "Nash", "Orla", "Pax", "Quillan", "Rhea",
            "Soren", "Tess", "Uriah", "Veda", "Wren", "Xanthe", "Yara", "Zuri", "Alden", "Briar",
            "Cyrus", "Dahlia", "Ezra", "Freya", "Gideon", "Harlow", "Iris", "Jett", "Koa", "Lark",
            "Mira", "Nash", "Orla", "Pax", "Quillan", "Rhea", "Soren", "Tess", "Uriah", "Veda",
    };

    public static final String[] DESCRIPTIONS = {
            "a brave warrior", "a cunning rogue", "a wise mage", "a mysterious wanderer", "a jovial trickster",
            "a stern guardian", "an enigmatic wanderer", "a gentle healer", "a fierce assassin", "a seasoned veteran",
            "a curious scholar", "a daring adventurer", "an elusive thief", "a charismatic leader",
            "a resourceful survivor",
            "a stealthy scout", "a relentless fighter", "a loyal companion", "a quick-witted trickster",
            "a battle-hardened warrior",
            "a mystical enchanter", "a sly strategist", "a powerful sorcerer", "a noble defender",
            "a fearless explorer",
            "a mysterious enigma", "a rugged nomad", "an ancient seer", "a playful spirit", "a silent observer",
            "a charismatic bard", "a wise elder", "an agile duelist", "a vibrant magician", "a daring pirate",
            "a thoughtful mentor", "a relentless seeker", "a kind-hearted sage", "a brave pioneer",
            "a resolute guardian",
            "a dynamic rebel", "a patient tactician", "a spirited wanderer", "a formidable champion",
            "a mystical druid",
            "an eccentric inventor", "a shrewd negotiator", "a loyal soldier", "a mystical prophet", "a gentle giant",
            "a skilled archer", "a powerful mage", "a nimble acrobat", "an experienced tracker",
            "a steadfast protector",
            "a crafty engineer", "an adventurous explorer", "a charismatic performer", "a diligent scholar",
            "a passionate revolutionary",
            "a seasoned strategist", "a resourceful alchemist", "a confident diplomat", "a daring fighter",
            "a wise guardian",
            "a playful rogue", "an honorable knight", "a mysterious cleric", "a subtle trickster",
            "a seasoned mercenary",
            "a bold ranger", "a keen observer", "a mystical monk", "a vibrant storyteller", "a fearless adventurer",
            "a subtle spy", "a rugged outlander", "a brave heart", "a determined seeker", "an enigmatic soul",
            "a wise tactician", "a joyful wanderer", "a fierce protector", "a noble spirit", "a creative innovator",
            "a daring challenger", "a bold visionary", "a spirited fighter", "a calm mediator",
            "a brilliant strategist",
            "a huge monster", "a powerful beast", "a cunning creature", "a wise sage", "a fierce guardian",
            "a gentle spirit", "a stealthy shadow", "a vibrant soul", "a mysterious entity", "a playful trickster",
            "a loyal friend", "a brave companion", "a fierce protector", "a wise mentor", "a cunning strategist",
            "a skilled warrior", "a resourceful survivor", "a daring adventurer", "a loyal ally", "a fierce rival",
            "a wise elder", "a cunning rogue", "a brave knight", "a skilled archer", "a powerful mage",
            "a stealthy assassin", "a clever bard", "a fierce warrior", "a wise sage", "a cunning trickster",
            "a brave explorer", "a loyal companion", "a fierce protector", "a wise mentor", "a cunning strategist",
            "a skilled warrior", "a resourceful survivor", "a daring adventurer", "a loyal ally", "a fierce rival",
            "a wise elder", "a cunning rogue", "a brave knight", "a skilled archer", "a powerful mage",
            "a stealthy assassin", "a clever bard", "a fierce warrior", "a wise sage", "a cunning trickster",
            "a brave explorer", "a loyal companion", "a fierce protector", "a wise mentor", "a cunning strategist",
    };
}
